<?php
# Only show partial if data is set
if(array_key_exists('job_position',$this->aPartialData)) {
    # add address form fields
    $aPositions = $this->aPartialData['job_position']['oPositionsDB'];
    $aFields = $this->aPartialData['job_position']['aFormFields'];

    if(count($aPositions) == 0) { ?>
        <div class="alert alert-info px-2 py-2">
            <?=$this->translate('No Positions yet')?>
        </div>
    <?php } else { ?>
        <ul class="list-group">
            <?php
            foreach($aPositions as $oPos) { ?>
                <li class="list-group-item">
                    <div class="row">
                        <?= $this->partial('partial/viewformfields', ['sFormName' => 'jobposition-single', 'sTab' => 'position-base', 'oItem' => $oPos, 'aFormFieldsByTab' => $aFields]); ?>
                    </div>
                </li>
                <?php
            }
            ?>
        </ul>
        <?php
    }
}
