<?php

?>
<ul class=list-group>
    <?php
    if(count($Positions)) {
        foreach($Positions as $oRow) {?>
            <li class="list-group-item">
                <div class="row">
                <!-- basicviewfields partial -->
                </div>
                Position<?=$oRow->getID()?> - <?=$oRow->description?>
            </li/>
            <?php
        }
    } else { ?>
            <div class="alert alert-info">No Position</div>

    <?php
    }

?>
</ul>